apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
spec:
  template:
    spec:
      containers:
        - name: db-migration
          image: rimgbulldo/symfony-demo:latest
          command: ["php", "bin/console", "doctrine:migrations:migrate", "--no-interaction"]
          env:
            - name: APP_ENV
              value: "prod"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-url
      restartPolicy: Never
