apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingoda-app
  namespace: lingoda-app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lingoda-app
  template:
    metadata:
      labels:
        app: lingoda-app
    spec:
      containers:
        - name: lingoda-app
          image: rimgbulldo/symfony-demo:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-url

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingoda-postgres
spec:
  selector:
    matchLabels:
      app: lingoda-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: lingoda-postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-password
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "lingoda_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
