<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGyRvnKs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGyRvnKs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGyRvnKs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGyRvnKs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGyRvnKs\App_KernelDevDebugContainer([
    'container.build_hash' => 'GyRvnKs',
    'container.build_id' => 'bd1521c3',
    'container.build_time' => 1710707138,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGyRvnKs');
